### ISSUE TITLE
Unknown vscode-remote netloc type: ssh-remote+p

### ISSUE THREAD

**Issue by kagurazakayashi** [sekai-soft/code-launcher#1]
- Windows 版本： 10,22H2 (19045.4170) x64
- code-launcher 版本：[Alpha release](https://github.com/sekai-soft/code-launcher/releases/tag/alpha)
- VSCode 版本：
```
code -v
  1.87.2
  863d2581ecda6849923a2118d93a088b0745d9d6
  x64
```
- 异常：解压缩 win.zip 并运行 Code Launcher.exe 后，直接收到报错：
```
Traceback (most recent call last):
  File "app.py", line 13, in <module>
  File "app.py", line 7, in main
  File "code_launcher_ui\my_frame.py", line 31, in __init__
  File "code_launcher_ui\my_frame.py", line 57, in renderMainUI
  File "code_launcher\read_vscode_state.py", line 48, in read_vscode_state
  File "code_launcher\parse_vscode_uri.py", line 86, in parse_vscode_uri
code_launcher.exception.CodeLauncherException: Unknown vscode-remote netloc type: ssh-remote+p
```

**Comment by KTachibanaM** [comment]
ssh remote 的打开方式尚未实现过

**Comment by KTachibanaM** [comment]
加上了 去原来的 release 页下载新的 zip
